### PR TITLE
Windows host initial support

### PR DESCRIPTION
**Pull request by qthree**
MVP for Windows host support. Works with Docker Toolbox (via VirtualBox) on Windows 10 Home. Untested with modern Docker for Windows (requires Windows 10 Pro and/or Insider Preview).
All tests are passing, both in Windows host (`cargo test`) and inside Linux guest (`cargo run -- test`), but otherwise this PR is a draft, not suitable for production.
It works for my workflow, but didn't touch anything related to mounting (but tests are passing, so idk) and remote caching.

XR6pJVW81x

**Status:** Sanity check required

**Fixes:** #262

### CODE REVIEW

**Comment by stepchowfun** [comment]
This is looking great. Let me know if/when you'd like me to review.

The unit tests don't bestow too much confidence when porting to a new platform, since they don't test platform-specific behavior. This repo has a few integration tests to make sure Toast works together with Docker and the host OS, but these are written as simple Bash scripts and it may be hard to run them on Windows (or maybe WSL makes this easy?). If we can get those to work, I'd be reasonably confident here.

I'd say the main things we should look out for are handling of file permissions and handling of absolute paths. Looks like this PR addresses these considerations.

Thanks for contributing to Toast!

**Comment by qthree** [comment]
Ok, so the first problem is line endings.
s0zRs2HIQS
`toast --shell` and `vi greet.sh` gives us this:
```
#!/bin/sh^M
set -euo pipefail^M
^M
echo 'Hello, World!'^M
```
This probably depends on Git for Windows settings, but i guess we need to convert line endings either way, right? So, unresolved questions:
1.  Should i convert line endings of files before adding them to tar archive?
2.  Should i convert them before or after hash computation?
3.  Should i just read the whole file to string, while converting it, or should i implement some smart Read wrapper?
4.  How do i detect text files apart from binary files?
5.  Should i convert line endings back for output files? How do i recognize host system preferred line endings? Should i add command line flag or settings field to toast file?

**Comment by qthree** [comment]
The second problem is with integration tests themselves.
`Git Bash` from `Git for Windows` can't handle non-existent symlink creation (i'm not sure what's the intention here)
```
$ ln -s non-existent symlink
ln: failed to create symbolic link 'symlink': No such file or directory
```
The third problem is with checking execution permission. Cause i don't know how can we check file permissions on windows, other then through git. Or by making all `.sh` files starting with `#!` executable.
Otherwise tests are passing
```
$ TOAST=D:\\rust\\toast\\target\\debug\\toast.exe ./integration-tests.sh
Toast location: D:\rust\toast\target\debug\toast.exe
Docker version 19.03.1, build 74b1e89e8a
Running integration test: integration-tests/base-images/alpine/run.sh
[INFO] Ready to run 3 tasks: create_user, i_am_root, and greet.
[INFO] Running task create_user…
[INFO] Running task i_am_root…
[INFO] Running task greet…
/scratch
user
Hello, World!
Running integration test: integration-tests/base-images/busybox/run.sh
[INFO] Ready to run 3 tasks: create_user, i_am_root, and greet.
[INFO] Running task create_user…
[INFO] Running task i_am_root…
[INFO] Running task greet…
/scratch
user
Hello, World!
Running integration test: integration-tests/base-images/centos/run.sh
[INFO] Ready to run 3 tasks: create_user, i_am_root, and greet.
[INFO] Running task create_user…
[INFO] Running task i_am_root…
[INFO] Running task greet…
/scratch
user
Hello, World!
Running integration test: integration-tests/base-images/debian/run.sh
[INFO] Ready to run 3 tasks: create_user, i_am_root, and greet.
[INFO] Running task create_user…
Adding user `user' ...
Adding new group `user' (1000) ...
Adding new user `user' (1000) with group `user' ...
Creating home directory `/home/user' ...
Copying files from `/etc/skel' ...
[INFO] Running task i_am_root…
[INFO] Running task greet…
/scratch
user
Hello, World!
Running integration test: integration-tests/base-images/fedora/run.sh
[INFO] Ready to run 3 tasks: create_user, i_am_root, and greet.
[INFO] Running task create_user…
[INFO] Running task i_am_root…
[INFO] Running task greet…
/scratch
user
Hello, World!
Running integration test: integration-tests/base-images/ubuntu/run.sh
[INFO] Ready to run 3 tasks: create_user, i_am_root, and greet.
[INFO] Running task create_user…
Adding user `user' ...
Adding new group `user' (1000) ...
Adding new user `user' (1000) with group `user' ...
Creating home directory `/home/user' ...
Copying files from `/etc/skel' ...
[INFO] Running task i_am_root…
[INFO] Running task greet…
/scratch
user
Hello, World!
Running integration test: integration-tests/input-paths/dir/run.sh
[INFO] Ready to run 1 task: list.
[INFO] Running task list…
drwxrwxrwx 2 root root 4096 Jan  1  1970 foo
Running integration test: integration-tests/input-paths/empty/run.sh
[INFO] Ready to run 1 task: list.
[INFO] Running task list…
drwxrwxrwx 2 root root 4096 Jan  1  1970 .
Running integration test: integration-tests/input-paths/nested-dir/run.sh
[INFO] Ready to run 1 task: list.
[INFO] Running task list…
drwxrwxrwx 3 root root 4096 Jan  1  1970 foo
drwxrwxrwx 2 root root 4096 Jan  1  1970 bar
```

**Comment by stepchowfun** [comment]
@qthree Thanks for the detailed investigation, and apologies for the slow response.

I understand there are three major questions here:

1. What to do about line endings
2. What to do about the non-existing symlink test
3. How to check permissions

For (1), I would prefer to avoid any solution that involves guessing whether files are "text" files and modifying their contents. I recommend that people configure Git using the `* binary` rule (which tells Git to not change line endings) and then have all collaborators on a project agree on a consistent line ending sequence (and configure their editors accordingly). For this project (Toast itself), that would be LF. (Perhaps I should add a `.gitattributes` file to this repo.)

For (2), the intention is that a symlink which points to a non-existent file is still just a regular file and should not cause any problems when copied into the container. Toast, like Git, does not follow symlinks and just treats them as regular files. The test basically ensures that the contents of symlinks (i.e., what they point to) are uninterpreted by Toast.

For (3), I am not very familiar with Windows. I did some quick Google-ing, and it seems that Windows does not have an execute permission like Unix does. I'm not sure exactly what Git does—perhaps it just stores the permission bit for each file and never actually queries the filesystem for it on Windows? For Toast, how about we just treat `*.exe` files as executable and all other files as not executable? So just check the file extension.

**Comment by stepchowfun** [comment]
Since you were able to get the integration tests to pass with some modification, I think that's good enough. I don't think we need to permanently get them to work on Windows, since the current CI system (Travis) doesn't do Windows builds anyway. I just wanted to get some confidence in this specific change, and we can figure out how to set up proper automated testing on Windows at a later date. I suspect I will have to switch from Travis to something like AppVeyor.

**Comment by stepchowfun** [comment]
Closing because https://github.com/stepchowfun/toast/pull/306 has landed.

**Pull request closed without merging**
