### PR TITLE
readme - add brew install instructions

### PR DESCRIPTION
**Pull request by tekumara**
Add brew install instructions to README.md

**Status:** Ready

### CODE REVIEW

**Comment by stepchowfun** [comment]
Oh wow, I didn't know about this. Someone created a Homebrew formula? Was it you? (If so, thank you!)

**Comment by tekumara** [comment]
It wasn't me. I just tried `brew install toast` and to my surprise, it worked!

**Comment by stepchowfun** [comment]
Amazing. I looked at the [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/toast.rb) and tried it out. Everything looks good to me. Thanks for this PR, and thanks to whomever created the formula (GitHub is having trouble showing me its commit history). I'll merge this now.

**Comment by stepchowfun** [comment]
Thanks @chenrui333 for your help on this! I'm still confused about the author of https://github.com/Homebrew/homebrew-core/pull/45705, but I see you've contributed too. Much appreciated!

**Pull request merged**
