### PR TITLE
feat: support `extra_docker_args` in toastfile

### PR DESCRIPTION
**Pull request by NOBLES5E**
A clear description of the change.

**Status:** Ready

**Fixes:** https://github.com/stepchowfun/toast/issues/362

### CODE REVIEW

**Comment by stepchowfun** [comment]
Hi @NOBLES5E, thank you for sponsoring Toast development! To show my gratitude, I have changed my mind and will merge this pull request later tonight or tomorrow.

If we ever switch to using Bollard/the Docker API instead of the Docker CLI in the future, then this feature will have to be removed per our discussion. But, for now, I am willing to support it (making no promises about the future, though).

**Comment by NOBLES5E** [comment]
@stepchowfun Awesome. And thanks for your great work!

**Comment by stepchowfun** [comment]
@NOBLES5E, I'm thinking about how this feature will interact with caching. The three options I'm considering:

1. `extra_docker_args` does not affect caching.
2. `extra_docker_args` is incorporated into the cache key (just like most of the other fields).
3. A task must have caching disabled in order to use `extra_docker_args`. This is the situation for `mount_paths` and `ports`.

I'm leaning toward (3), since you could use this feature to configure networking, set up interactive I/O, attach storage volumes, and other things that probably should be considered incompatible with caching. Would that work for you?

**Comment by stepchowfun** [comment]
Would you mind giving me the [permissions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to push to this branch? There are a few small changes I'd like to make (I can also just post a diff here if that works better for you).

**Comment by NOBLES5E** [comment]
> @NOBLES5E, I'm thinking about how this feature will interact with caching. The three options I'm considering:
> 
>     1. `extra_docker_args` does not affect caching.
> 
>     2. `extra_docker_args` is incorporated into the cache key (just like most of the other fields).
> 
>     3. A task must have caching disabled in order to use `extra_docker_args`. This is the situation for `mount_paths` and `ports`.
> 
> 
> I'm leaning toward (3), since you could use this feature to configure networking, set up interactive I/O, attach storage volumes, and other things that probably should be considered incompatible with caching. Would that work for you?

I agree. I would say (3) is more consistent with toast's current implementation (since for example `mount_path` can be specified within `extra_docker_args`).

**Comment by stepchowfun** [comment]
Sounds good—I've added that validation to this PR. FYI I also renamed `extra_docker_args` to `extra_docker_arguments` (no need to abbreviate, since there is already an even longer key: `output_paths_on_failure `). I'll merge this now.

**Pull request merged**
